name: Flutter Nightly Build

on:
  schedule:
    # schedule build every 10 night
    - cron: "0 0 */10 * *"
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    #uses: ./.github/workflows/flutter-build-custom-mods.yml
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly"
